"""
Per-store configuration: branding, Odoo website IDs,
product language, and greeting tone for all 7 stores.
"""

STORES = {
    "LongIslandConvenience": {
        "name":        "Long Island Convenience",
        "short":       "LIC",
        "domain":      "longislandconvenience.com",
        "odoo_site_id": 1,
        "emoji":       "🏪",
        "grad_color1": "#1a1a2e",   # deep navy
        "grad_color2": "#16213e",
        "accent":      "#e94560",
        "text_light":  "#ffffff",
        "tagline":     "Your neighborhood store — open every day, Long Island",
        "offer_verb":  "stock up on",
        "offer_noun":  "everyday essentials, snacks & drinks",
        "cta_text":    "Shop Deals",
        "phone":       "(516) 555-0100",
        "address":     "Long Island, NY",
    },
    "LongIslandBalloons": {
        "name":        "Long Island Balloons Decor",
        "short":       "LIBD",
        "domain":      "longislandballoonsdecor.com",
        "odoo_site_id": 38,
        "emoji":       "🎈",
        "grad_color1": "#ff6b6b",
        "grad_color2": "#feca57",
        "accent":      "#ffffff",
        "text_light":  "#333333",
        "tagline":     "Balloon arrangements & party decoration — Long Island",
        "offer_verb":  "decorate with",
        "offer_noun":  "custom balloon arrangements & party packages",
        "cta_text":    "Book Decoration",
        "phone":       "(516) 555-0200",
        "address":     "Long Island, NY",
    },
    "LIGiftBasket": {
        "name":        "LI Gift Basket",
        "short":       "LIGB",
        "domain":      "ligiftbasket.com",
        "odoo_site_id": 37,
        "emoji":       "🎁",
        "grad_color1": "#667eea",
        "grad_color2": "#764ba2",
        "accent":      "#FFD700",
        "text_light":  "#ffffff",
        "tagline":     "Curated gift baskets — Plainview, Long Island NY",
        "offer_verb":  "gift",
        "offer_noun":  "beautiful curated gift baskets from $35",
        "cta_text":    "Shop Gift Baskets",
        "phone":       "(516) 555-0300",
        "address":     "Plainview, Long Island, NY 11803",
    },
    "LongIslandPrintMail": {
        "name":        "Long Island Print & Mail",
        "short":       "LIPM",
        "domain":      "longislandprintandmail.com",
        "odoo_site_id": 39,
        "emoji":       "🖨️",
        "grad_color1": "#2c3e50",
        "grad_color2": "#3498db",
        "accent":      "#f39c12",
        "text_light":  "#ffffff",
        "tagline":     "Custom printing, cards & mailing — Long Island",
        "offer_verb":  "print",
        "offer_noun":  "custom cards, invitations & banners",
        "cta_text":    "Order Print",
        "phone":       "(516) 555-0400",
        "address":     "Long Island, NY",
    },
    "LongIslandCards": {
        "name":        "Long Island Card",
        "short":       "LIC2",
        "domain":      "longislandcards.com",
        "odoo_site_id": 36,
        "emoji":       "🃏",
        "grad_color1": "#134e5e",
        "grad_color2": "#71b280",
        "accent":      "#FFD700",
        "text_light":  "#ffffff",
        "tagline":     "Sports cards, collectibles & greeting cards — Long Island",
        "offer_verb":  "celebrate with",
        "offer_noun":  "sports cards, collectibles & greeting cards",
        "cta_text":    "Browse Cards",
        "phone":       "(516) 555-0500",
        "address":     "Long Island, NY",
    },
    "HirenKumar": {
        "name":        "JHD Advisor",
        "short":       "HKA",
        "domain":      "jhdadvisor.com",
        "odoo_site_id": 41,
        "emoji":       "💼",
        "grad_color1": "#0f0c29",
        "grad_color2": "#302b63",
        "accent":      "#c0a060",
        "text_light":  "#ffffff",
        "tagline":     "Financial & business advisory — Plainview, Long Island NY",
        "offer_verb":  "plan for",
        "offer_noun":  "your financial future — free consultation",
        "cta_text":    "Book Free Consult",
        "phone":       "(516) 555-0600",
        "address":     "605 Old Country Rd, Plainview, NY 11803",
    },
    "ConsultCyber": {
        "name":        "Consult Cyber",
        "short":       "CC",
        "domain":      "consultcyber.net",
        "odoo_site_id": 29,
        "emoji":       "🔐",
        "grad_color1": "#0a3d62",
        "grad_color2": "#1e3799",
        "accent":      "#00d2d3",
        "text_light":  "#ffffff",
        "tagline":     "Cybersecurity & IT consulting — Long Island NY (est. 1998)",
        "offer_verb":  "secure",
        "offer_noun":  "your business with expert IT & cybersecurity",
        "cta_text":    "Get IT Assessment",
        "phone":       "212-564-8585",
        "address":     "605 Old Country Rd, Plainview, NY 11803",
    },
}
